### PR TITLE
Fixed Wrong placeholder present in the sign-in page 

### LINKED ISSUE #78: Wrong placeholder has been provided for password in the Sign In section
# Description
The wrong placeholder for password in the sign-in form should be replaced with "Enter Your Password."

## Type of issue
- [x] Bug

## Checklist

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] I have checked previous issues to avoid duplicates.
- [x] I have added screenshots in case of bugs/feature updates.
- [x] This issue will be meaningful for the project.

### In case of bugs

- [x] I have added screenshots of the bug.
- [x] I have added steps to reproduce the bug.
- [x] I have proposed a possible solution for the bug.

### Screenshots
Capture4

### PR DESCRIPTION
**Pull request by AdityaJ7**
# Description

Fixed the placeholder for the password section present in the sign-in page of the website.

Fixes #78 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Frontend

## Checklist

Please tick all the boxes that are fulfilled by your Pull Request.

- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] My code additions/changes do not produce any warnings.

### CODE REVIEW

File: src/components/Signin.jsx [hunk 1]
```diff
@@ -162,7 +162,7 @@ const Signin = () => {
                                     name="password"
                                     value={password}
                                     onChange={e => onChange(e)}
-                                    placeholder="Write the subject of the mail here."
+                                    placeholder="Enter your password here."
                                     required
                                 />
```
Comment (ashishnagpal2498) [inline src/components/Signin.jsx:167]: SignIn and Sign Out buttons ?, heading as well as all the oAuth Options. Correct that

**Review by ashishnagpal2498 — CHANGES_REQUESTED** [review]

File: src/components/Signin.jsx (hunk 1 above)
Comment (AdityaJ7) [reply src/components/Signin.jsx:167]: ok I thought someone less is  working on that, will do that as well
